version: "3"

tasks:
  default:
    - task: lint
    - task: fix
    - task: spell-check
    - task: format

  run:
    cmd: bash ./run.sh

  stop:
    ignore_error: true
    cmds:
      - kill $(cat .pid)
      - rm .pid

  lint:
    cmds:
      - ruff check --respect-gitignore src tools
      - pylint -f colorized src
      - pyright src tools

  format:
    ignore_error: true
    cmd: ruff format --respect-gitignore src tools

  fix:
    cmd: ruff check --respect-gitignore --fix src tools

  spell-check:
    cmd: cspell lint "**"

  dev-install:
    cmds:
      - pip install --upgrade ruff pyright pre-commit pylint

  dev-setup:
    deps:
      - dev-install
      - create-config
    cmds:
      - npm install -g cspell @cspell/dict-ru_ru
      - cspell link add @cspell/dict-ru_ru
      - pre-commit install

  clean:
    cmds:
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - rm -rf nohup.out .pid site .*_cache release_body.md *.log

  create-config:
    ignore_error: true
    cmd: python3 tools/create_config.py

  docs-setup:
    cmds:
      - pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin

  release:
    cmd: python3 tools/bump_version.py {{.CLI_ARGS}}
