name: Send release notification

on:
  release:
    types:
      - prereleased
      - released


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install --upgrade pip && pip install -r requirements.txt

    - name: Send release notification
      run: python tools/send_release_notification.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
